name: vtpk_devel_p311
dependencies: 
    - python=3.11 
    - ipython
    - pyproj
    - geopandas
    - shapely
    - mapbox-vector-tile
    - ruff
    - build
    - twine
    - coverage
    - pytest
    - mypy
    - grayskull
    - pip
    - pip:
      - types-shapely
